# Generated by Django 5.2 on 2025-05-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
