# Generated by Django 5.2 on 2025-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
