# Generated by Django 5.2 on 2025-04-23 00:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_enrroll_enrrollresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrroll',
            new_name='Comments',
        ),
    ]
