# Generated by Django 5.2 on 2025-05-06 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_paypal_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleClase', models.CharField(max_length=250)),
                ('slugClase', models.SlugField(blank=True, null=True)),
                ('fileClase', models.FileField(upload_to='files', verbose_name='Archivo')),
                ('bannerClase', models.ImageField(upload_to='clase_banners')),
                ('descriptionClase', models.CharField(max_length=450)),
                ('nivel', models.CharField(choices=[('Basico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=20)),
                ('class_date', models.DateField(auto_now_add=True)),
                ('productClase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
