# Generated by Django 3.2.19 on 2025-10-19 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='usuarios_pagados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que han pagado por esta clase', related_name='clases_pagadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
