# Generated by Django 5.2 on 2025-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_comment_product_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pay_method',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
