# Generated by Django 3.2.19 on 2026-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_clase_usuarios_pagados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_request_status',
            field=models.CharField(choices=[('none', 'No solicitado'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='none', max_length=10),
        ),
    ]
