# Generated by Django 3.2.19 on 2026-08-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20260804_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
