# Generated by Django 3.2.19 on 2026-08-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_profile_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('profession', models.CharField(max_length=150, verbose_name='Profesión')),
                ('specialty', models.CharField(max_length=150, verbose_name='Materia o especialidad a enseñar')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('certificate', models.FileField(upload_to='teacher_certificates', verbose_name='Certificado')),
                ('bio', models.TextField(max_length=1000, verbose_name='Cuéntanos sobre tu experiencia')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_application', to='store.profile')),
            ],
        ),
    ]
