# Generated by Django 3.2.19 on 2026-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='es_preview',
            field=models.BooleanField(default=False, help_text='Si está marcado, cualquier visitante puede verla sin comprar', verbose_name='Vista previa gratuita'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración total (minutos)'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, default='Español', max_length=50, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='product',
            name='learning_points',
            field=models.TextField(blank=True, default='', help_text='Un punto por línea', verbose_name='Lo que aprenderás'),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Un requisito por línea', verbose_name='Requisitos previos'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.TextField(blank=True, default='', help_text='Un público por línea', verbose_name='Dirigido a'),
        ),
    ]
