# Generated by Django 3.2.19 on 2026-08-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20260811_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nivel',
            field=models.CharField(choices=[('Gratis', 'Versión gratuita'), ('Pago', 'Versión de pago')], default='Gratis', max_length=20),
        ),
    ]
