# Generated by Django 3.2.19 on 2026-08-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_clase_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='materialClase',
            field=models.FileField(blank=True, null=True, upload_to='materiales', verbose_name='Material descargable (opcional)'),
        ),
    ]
