# Generated by Django 3.2.19 on 2026-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_certificado_entregatarea_intentoquiz_opcion_pregunta_quiz_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_access_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Si lo dejas vacío, se usará el precio normal del curso', max_digits=6, null=True, verbose_name='Precio de acceso a todas las clases de pago'),
        ),
    ]
