# Generated by Django 3.2.19 on 2026-08-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_full_access_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('discount_percent', models.PositiveSmallIntegerField(help_text='Porcentaje de descuento, de 1 a 100', verbose_name='Descuento (%)')),
                ('active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido hasta (opcional)')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usos máximos (opcional)')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='store.product')),
            ],
        ),
    ]
