# Generated by Django 3.2.19 on 2026-08-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yape_plin_number',
            field=models.CharField(blank=True, help_text='Celular asociado a tu Yape o Plin, para recibir tus pagos', max_length=15, verbose_name='Número Yape/Plin'),
        ),
    ]
