# Generated by Django 5.2 on 2025-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_time_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
