# Generated by Django 3.2.19 on 2025-05-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_izipaypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IzipayPayment',
        ),
    ]
