# Generated by Django 3.2.19 on 2025-10-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_izipaypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseAvanzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleClase', models.CharField(max_length=255)),
                ('descriptionClase', models.TextField()),
                ('bannerClase', models.ImageField(upload_to='banners_clases/')),
                ('fileClase', models.FileField(upload_to='clases_avanzado/')),
                ('price', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
