# Generated by Django 5.2 on 2025-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_time_begin_order_time_final_order_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='time_final',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='topic',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tiempo de fin'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tiempo de inicio'),
        ),
        migrations.AddField(
            model_name='order',
            name='study_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema que desea estudiar'),
        ),
    ]
