# Generated by Django 3.2.19 on 2025-10-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_claseavanzado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseAvanzado',
        ),
    ]
