# Generated by Django 5.2 on 2025-04-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_order_time_begin_remove_order_time_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='study_topic',
        ),
    ]
