# Generated by Django 5.2 on 2025-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_end_time_remove_order_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='study_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
