# Generated by Django 3.2.19 on 2026-08-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_delete_claseavanzado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='instructor_earning',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_out',
            field=models.BooleanField(default=False, verbose_name='Ya liquidado al profesor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
    ]
