# Generated by Django 5.2 on 2025-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_end_time_order_start_time_order_study_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tema_estudio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
