# Generated by Django 5.2 on 2025-04-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_orderitem_tema_estudio_orderitem_tiempo_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tema_estudio',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tiempo_fin',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tiempo_inicio',
        ),
    ]
