# Generated by Django 5.2 on 2025-04-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_orderitem_tema_estudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='study_topic',
        ),
    ]
