# Generated by Django 5.2 on 2025-04-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_order_end_time_remove_order_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tema_estudio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
