# Generated by Django 5.2 on 2025-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_order_tema_estudio_order_tiempo_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_tema_estudio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_tiempo_fin',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_tiempo_inicio',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
