# Generated by Django 5.2 on 2025-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_shippingaddress_shipping_tema_estudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_tiempo_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_tiempo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
