# Generated by Django 5.2 on 2025-04-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_shippingaddress_shipping_tiempo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
