# Generated by Django 5.2 on 2025-04-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_shippingaddress_shipping_tiempo_fin_and_more'),
        ('store', '0007_alter_comment_product_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='store.product'),
        ),
    ]
