# Generated by Django 5.2 on 2025-04-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
